add some semicolons

diff --git a/.github/workflows/check_backend_pom_version.yaml b/.github/workflows/check_backend_pom_version.yaml
--- a/.github/workflows/check_backend_pom_version.yaml
+++ b/.github/workflows/check_backend_pom_version.yaml
@@ -26,19 +26,19 @@ jobs:
       
       - name: Check Pom Version
         run: >
-          git fetch
-          git branch -a
+          git fetch;
+          git branch -a;
 
-          LOCAL_VERSION=$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="version"]/text()' backend/pom.xml)
-          echo "Local version: $LOCAL_VERSION"
+          LOCAL_VERSION=$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="version"]/text()' backend/pom.xml);
+          echo "Local version: $LOCAL_VERSION";
 
-          git fetch origin master
-          git checkout origin/master -- backend/pom.xml
+          git fetch origin master;
+          git checkout origin/master -- backend/pom.xml;
 
-          REMOTE_VERSION=$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="version"]/text()' backend/pom.xml)
-          echo "Remote version: $REMOTE_VERSION"
+          REMOTE_VERSION=$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="version"]/text()' backend/pom.xml);
+          echo "Remote version: $REMOTE_VERSION";
 
           if [ "$REMOTE_VERSION" == "$LOCAL_VERSION" ]; then
-            echo "::error::The version in pom.xml is the same as the one on master. Please update the version in your pull request."
-            exit 1
+            echo "::error::The version in pom.xml is the same as the one on master. Please update the version in your pull request.";
+            exit 1;
           fi
