change the check

diff --git a/.github/workflows/check_backend_pom_version.yml b/.github/workflows/check_backend_pom_version.yml
--- a/.github/workflows/check_backend_pom_version.yml
+++ b/.github/workflows/check_backend_pom_version.yml
@@ -1,38 +1,30 @@
-name: Check backend/src files changed
+name: Check Pom Version on PR to master
+
 on:
   pull_request:
     branches:
       - master
+    paths:
+      - 'backend/src/**'
 
 jobs:
-  conditional_job_check_files:
+  check-pom-version:
     runs-on: ubuntu-latest
-    # Declare outputs for next jobs
-    outputs:
-      docs_changed: ${{ steps.check_file_changed.outputs.docs_changed }}
+
     steps:
     - uses: actions/checkout@v2
+
+    - name: Setup Java
+      uses: actions/setup-java@v2
       with:
-        # Checkout as many commits as needed for the diff
-        fetch-depth: 2
-    - shell: pwsh
-      id: check_file_changed
+        java-version: '11'
+
+    - name: Check Pom Version
       run: |
-        # Diff HEAD with the previous commit
-        $diff = git diff --name-only HEAD^ HEAD
+        REMOTE_VERSION=$(git show origin/master:backend/pom.xml | grep -o '<version>.*</version>' | sed 's/<version>//g' | sed 's/<\/version>//g')
+        LOCAL_VERSION=$(cat backend/pom.xml | grep -o '<version>.*</version>' | sed 's/<version>//g' | sed 's/<\/version>//g')
 
-        # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
-        $SourceDiff = $diff | Where-Object { $_ -match '^backend/src/'}
-        $HasDiff = $SourceDiff.Length -gt 0
-
-        # Set the output named "docs_changed"
-        Write-Host "::set-output name=docs_changed::$HasDiff"
-
-  # Run the job only with "docs_changed" equals "True"
-  conditional_job:
-    runs-on: ubuntu-latest
-    needs: [ conditional_job_check_files ]
-    if: needs.conditional_job_check_files.outputs.docs_changed == 'True'
-    steps:
-    - shell: pwsh
-      run: echo publish docs
+        if [ "$REMOTE_VERSION" != "$LOCAL_VERSION" ]; then
+          echo "::error::The version in pom.xml differs from the one on remote master. Please update the version in your pull request."
+          exit 1
+        fi
